const Items = [
  {
    tam: 'அரிசி',
    image: 'rice.png',
    unit: 'KG',
    quantity: 1,
    max: 10,
    price: 188,
    sin: 'සහල්',
    id: '1',
    eng: 'Rice',
  },
  {
    tam: 'உ.கிழங்கு',
    image: 'potatoe.png',
    unit: 'KG',
    quantity: 1,
    max: 2,
    price: 190,
    sin: 'අල',
    id: '10',
    eng: 'Potatoes',
  },
  {
    tam: 'ரின் மீன்',
    image: 'tin.jpeg',
    unit: 'TIN',
    max: 2,
    price: 650,
    sin: 'ටින් මාළු',
    id: '11',
    quantity: 1,
    eng: 'Tin fish',
  },
  {
    tam: 'முட்டை',
    image: 'egg.png',
    unit: 'Egg',
    quantity: 1,
    max: 20,
    sin: 'බිත්තර',
    id: '12',
    eng: 'Eggs',
    price: 50,
  },
  {
    tam: 'உப்பு',
    image: 'salt.png',
    unit: 'PKT',
    quantity: 1,
    max: 1,
    price: 110,
    sin: 'ලුණු',
    id: '13',
    eng: 'Salt',
  },
  {
    tam: 'தே.எண்ணெய்',
    image: 'coconut-oil.png',
    unit: 'L',
    quantity: 1,
    max: 2,
    price: 550,
    sin: 'පොල් තෙල්',
    id: '14',
    eng: 'Coconut oil',
  },
  {
    tam: 'சோயா',
    image: 'soya.png',
    unit: 'G',
    price: 300,
    sin: 'සෝයා',
    id: '15',
    eng: 'Soya',
    max: 500,
    quantity: 500,
  },
  {
    tam: 'மிளகாய் தூள்',
    image: 'red-chilly-powder.png',
    unit: 'G',
    quantity: 250,
    price: 375,
    sin: 'මිරිස් කුඩු',
    id: '16',
    max: 250,
    eng: 'Chili Powder',
  },
  {
    tam: 'மஞ்சள் தூள்',
    image: 'turmeric.png',
    unit: 'G',
    quantity: 50,
    price: 125,
    sin: 'කහ',
    id: '17',
    eng: 'Turmeric',
    max: 50,
  },
  {
    tam: 'கறி பவுடர்',
    image: 'curry.png',
    unit: 'G',
    quantity: 250,
    price: 500,
    sin: 'තුනපහ කුඩු',
    id: '18',
    eng: 'Curry Powder',
    max: 250,
  },
  {
    tam: 'செத்தல்',
    image: 'dry-chilly.png',
    unit: 'G',
    price: 275,
    sin: 'මිරිස්',
    id: '19',
    quantity: 250,
    max: 250,
    eng: 'Dry Chili',
  },
  {
    tam: 'கோ. மாவு',
    image: 'wheat.png',
    unit: 'KG',
    max: 8,
    price: 200,
    sin: 'තිරිඟු පිටි',
    id: '2',
    eng: 'Wheat Flour',
    quantity: 1,
  },
  {
    tam: 'மல்லி',
    image: 'coriander.png',
    unit: 'G',
    quantity: 250,
    price: 100,
    sin: 'කොත්තමල්ලි',
    id: '20',
    eng: 'Coriander',
    max: 250,
  },
  {
    tam: 'மிளகு',
    image: 'pepper.png',
    unit: 'G',
    quantity: 50,
    price: 120,
    sin: 'ගම්මිරිස්',
    id: '21',
    eng: 'Pepper',
    max: 50,
  },
  {
    tam: 'பூண்டு',
    image: 'garlic.png',
    unit: 'G',
    quantity: 500,
    sin: 'සුදුලූණු',
    id: '22',
    eng: 'Garlic',
    max: 500,
    price: 260,
  },
  {
    tam: 'லைப் போய்',
    image: 'life.png',
    unit: 'PKT',
    quantity: 1,
    max: 2,
    price: 160,
    sin: 'ලයිෆ්බෝය්  සබන්',
    id: '23',
    eng: 'LifeBouy Soap',
  },
  {
    tam: 'Baby Soap',
    image: 'baby.png',
    unit: 'PKT',
    quantity: 1,
    sin: 'බේබි සබන්',
    id: '24',
    eng: 'Baby Soap',
    price: 190,
    max: 3,
  },
  {
    tam: 'ஈவா',
    image: 'eva.png',
    unit: 'PKT',
    quantity: 1,
    max: 2,
    price: 270,
    sin: 'ඊවා',
    id: '25',
    eng: 'Eva',
  },
  {
    tam: 'பனதால்',
    image: 'Panadol.jpg',
    unit: 'CRD',
    quantity: 1,
    max: 2,
    price: 50,
    sin: 'පැනඩෝල්',
    id: '26',
    eng: 'Panadol',
  },
  {
    tam: 'வேறு பொருட்கள்',
    image: 'other.png',
    unit: 'LOT',
    quantity: 1,
    id: '27',
    max: 691,
    sin: 'අනික්කුත්',
    eng: 'Other',
  },
  {
    tam: 'அ. மாவு',
    image: 'rice-flour.png',
    unit: 'KG',
    quantity: 1,
    max: 5,
    price: 218,
    sin: 'හාල් පිටි',
    id: '3',
    eng: 'Rice Flour',
  },
  {
    tam: 'தேயிலை',
    image: 'tea.png',
    unit: 'G',
    quantity: 500,
    price: 750,
    sin: 'තේ කොළ',
    id: '4',
    eng: 'Tea',
    max: 500,
  },
  {
    tam: 'சீனி',
    image: 'sugar.png',
    unit: 'KG',
    quantity: 1,
    max: 3,
    price: 268,
    sin: 'සීනි',
    id: '5',
    eng: 'Sugar',
  },
  {
    tam: 'பெ. வெங்காயம்',
    image: 'onion.png',
    unit: 'KG',
    max: 2,
    price: 220,
    sin: 'ලොකු ලූනු',
    id: '6',
    eng: 'Big onion',
    quantity: 1,
  },
  {
    tam: 'பா.பயறு',
    image: 'green.png',
    unit: 'KG',
    quantity: 1,
    max: 1,
    price: 1000,
    sin: 'මුං ඇට',
    id: '7',
    eng: 'Green Gramme',
  },
  {
    tam: 'பருப்பு',
    image: 'dhal.png',
    unit: 'G',
    sin: 'මයිසූර් පරිප්පු',
    id: '8',
    eng: 'Red Dhal',
    max: 3500,
    quantity: 3500,
    price: 1120,
  },
  {
    tam: 'கடலை',
    image: 'chick.png',
    unit: 'KG',
    quantity: 1,
    max: 1,
    price: 650,
    sin: 'කඩල',
    id: '9',
    eng: 'Chickpeas',
  },
];

export default Items;
